/* 
   GENERATED BY azuriraj-projekte.js
   ------------------------------------
   Ukoliko zelis manualno mijenjati naslove, dodavati opise, 
   ili mijenjati 'cover' sliku, napravi to slobodno ovdje!
   Samo pazi da ne pregazis ovu datoteku ponovnim pokretanjem skripte
   bez arhiviranja tvojih promjena. 
*/

const PROJECT_ALBUMS = [
  {
    "id": 1,
    "title": "3d-motivi",
    "slug": "3d-motivi",
    "subtitle": "Kolekcija fotografija iz projekta. Uredivo manualno u projects-data.js.",
    "cover": "Projekti/3d-motivi/IMG_3014-HDR.jpg",
    "images": [
      "Projekti/3d-motivi/3D_BOZICNE_KUGLE-ST-920-3D-46-scaled.jpg",
      "Projekti/3d-motivi/IMG_2977.jpg",
      "Projekti/3d-motivi/IMG_3014-HDR.jpg",
      "Projekti/3d-motivi/IMG_3059-HDR.jpg",
      "Projekti/3d-motivi/IMG_3127-HDR.jpg",
      "Projekti/3d-motivi/IMG_3217.jpg",
      "Projekti/3d-motivi/IMG_3235-HDR.jpg",
      "Projekti/3d-motivi/IMG_3241-HDR.jpg",
      "Projekti/3d-motivi/IMG_3314-HDR.jpg",
      "Projekti/3d-motivi/IMG_5404-HDR-1536x987.jpg",
      "Projekti/3d-motivi/PAKET_S_PROLAZOM-ST-653-3D-04-scaled.jpg",
      "Projekti/3d-motivi/PINGVIN-ST-665-3D-07.jpg",
      "Projekti/3d-motivi/zeko-1.jpg"
    ],
    "order": 0
  },
  {
    "id": 2,
    "title": "3d-premium",
    "slug": "3d-premium",
    "subtitle": "Kolekcija fotografija iz projekta. Uredivo manualno u projects-data.js.",
    "cover": "Projekti/3d-premium/IMG_3314-HDR.jpg",
    "images": [
      "Projekti/3d-premium/20201217-A7B03570-scaled.jpg",
      "Projekti/3d-premium/20201217-A7B03584-scaled.jpg",
      "Projekti/3d-premium/3D_BOZICNE_KUGLE-ST-920-3D-46-scaled.jpg",
      "Projekti/3d-premium/Bik01.jpg",
      "Projekti/3d-premium/Bik02.jpg",
      "Projekti/3d-premium/DSC8091-scaled.jpg",
      "Projekti/3d-premium/DSC8102-3-scaled.jpg",
      "Projekti/3d-premium/Dnevni_boravak-1.jpeg",
      "Projekti/3d-premium/IMG_2977.jpg",
      "Projekti/3d-premium/IMG_3217.jpg",
      "Projekti/3d-premium/IMG_3314-HDR.jpg",
      "Projekti/3d-premium/Naslon01.jpg",
      "Projekti/3d-premium/PAKET_S_PROLAZOM-ST-653-3D-04-scaled.jpg",
      "Projekti/3d-premium/Prolaz01.jpg",
      "Projekti/3d-premium/Sjedalica01.jpg",
      "Projekti/3d-premium/Sjedalica02.jpg",
      "Projekti/3d-premium/Vucko.jpg",
      "Projekti/3d-premium/Zvijezde.jpg",
      "Projekti/3d-premium/image0.jpeg",
      "Projekti/3d-premium/zeko-1.jpg"
    ],
    "order": 1
  },
  {
    "id": 3,
    "title": "gradovi-i-opcine",
    "slug": "gradovi-i-opcine",
    "subtitle": "Kolekcija fotografija iz projekta. Uredivo manualno u projects-data.js.",
    "cover": "Projekti/gradovi-i-opcine/IMG_3387-HDR (1).jpg",
    "images": [
      "Projekti/gradovi-i-opcine/20201217-A7B03584-1536x1024.jpg",
      "Projekti/gradovi-i-opcine/DSC8091-1536x1024.jpg",
      "Projekti/gradovi-i-opcine/DSC8091-scaled.jpg",
      "Projekti/gradovi-i-opcine/Dubrovnik_kugla-1536x1024.jpg",
      "Projekti/gradovi-i-opcine/IMG_2792.jpg",
      "Projekti/gradovi-i-opcine/IMG_3047-HDR-2048x1366.jpg",
      "Projekti/gradovi-i-opcine/IMG_3196-HDR-1-1536x1024.jpg",
      "Projekti/gradovi-i-opcine/IMG_3314-HDR-1-1536x1024.jpg",
      "Projekti/gradovi-i-opcine/IMG_3314-HDR-2048x1366.jpg",
      "Projekti/gradovi-i-opcine/IMG_3387-HDR (1).jpg",
      "Projekti/gradovi-i-opcine/IMG_3387-HDR.jpg",
      "Projekti/gradovi-i-opcine/IMG_3420-HDR-1-1536x1024.jpg",
      "Projekti/gradovi-i-opcine/IMG_3420-HDR-1.jpg",
      "Projekti/gradovi-i-opcine/IMG_3468.jpg",
      "Projekti/gradovi-i-opcine/IMG_3498-HDR (1).jpg",
      "Projekti/gradovi-i-opcine/IMG_3498-HDR.jpg",
      "Projekti/gradovi-i-opcine/IMG_3527-HDR-1-1536x1024.jpg",
      "Projekti/gradovi-i-opcine/Split_Marmontova-scaled.jpg",
      "Projekti/gradovi-i-opcine/Split_Riva-2-2048x1536.jpg",
      "Projekti/gradovi-i-opcine/Stradun_kugle-1-scaled.jpg",
      "Projekti/gradovi-i-opcine/Zagreb_HNK.jpg",
      "Projekti/gradovi-i-opcine/Zagreb_Markov_trg.jpg",
      "Projekti/gradovi-i-opcine/bozicne_dekoracije-1-2048x1365.jpg",
      "Projekti/gradovi-i-opcine/svjetlosne-dekoracije-dubrovnik-Large (1).jpg",
      "Projekti/gradovi-i-opcine/svjetlosne-dekoracije-dubrovnik-Large.jpg",
      "Projekti/gradovi-i-opcine/y.jpg"
    ],
    "order": 2
  },
  {
    "id": 4,
    "title": "poslovni-i-privatni-objekti",
    "slug": "poslovni-i-privatni-objekti",
    "subtitle": "Kolekcija fotografija iz projekta. Uredivo manualno u projects-data.js.",
    "cover": "Projekti/poslovni-i-privatni-objekti/IMG_2823-HDR.jpg",
    "images": [
      "Projekti/poslovni-i-privatni-objekti/IMG_2823-HDR.jpg",
      "Projekti/poslovni-i-privatni-objekti/IMG_2850-1.jpg",
      "Projekti/poslovni-i-privatni-objekti/IMG_3088-HDR-1.jpg",
      "Projekti/poslovni-i-privatni-objekti/IMG_3109-HDR.jpg",
      "Projekti/poslovni-i-privatni-objekti/IMG_3163-HDR.jpg",
      "Projekti/poslovni-i-privatni-objekti/IMG_3190-HDR.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_01-2-scaled.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_02-1-scaled.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_03-2-scaled.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_03-scaled.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_04-1-1536x1152.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_05-2-scaled.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_06-1-scaled.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_07-1-e1773269209741 (1).jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_07-1-e1773269209741.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_08-1-1536x1152.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_09-scaled.jpg",
      "Projekti/poslovni-i-privatni-objekti/Mall_of_Split_14 (1).jpg"
    ],
    "order": 3
  },
  {
    "id": 5,
    "title": "salajland",
    "slug": "salajland",
    "subtitle": "Kolekcija fotografija iz projekta. Uredivo manualno u projects-data.js.",
    "cover": "Projekti/salajland/Uskrs_11-1.png",
    "images": [
      "Projekti/salajland/Uskrs_11-1.png",
      "Projekti/salajland/Uskrs_12-1.png",
      "Projekti/salajland/Uskrs_13-1.jpg"
    ],
    "order": 4
  },
  {
    "id": 6,
    "title": "uskrsne-dekoracije",
    "slug": "uskrsne-dekoracije",
    "subtitle": "Kolekcija fotografija iz projekta. Uredivo manualno u projects-data.js.",
    "cover": "Projekti/uskrsne-dekoracije/Uskrs_01-1.jpg",
    "images": [
      "Projekti/uskrsne-dekoracije/Uskrs_01-1.jpg",
      "Projekti/uskrsne-dekoracije/Uskrs_02.jpg",
      "Projekti/uskrsne-dekoracije/Uskrs_05-1-scaled-e1773259367280-2048x1339.jpg",
      "Projekti/uskrsne-dekoracije/Uskrs_05-1-scaled-e1773259367280.jpg",
      "Projekti/uskrsne-dekoracije/Uskrs_07-1-1536x1153.jpg",
      "Projekti/uskrsne-dekoracije/Uskrs_07-1-scaled.jpg",
      "Projekti/uskrsne-dekoracije/Uskrs_08-1-scaled.jpg",
      "Projekti/uskrsne-dekoracije/Uskrs_09-1.jpg",
      "Projekti/uskrsne-dekoracije/zeko-1-1536x1017.jpg"
    ],
    "order": 5
  },
  {
    "id": 7,
    "title": "vjencanja-i-zabave",
    "slug": "vjencanja-i-zabave",
    "subtitle": "Kolekcija fotografija iz projekta. Uredivo manualno u projects-data.js.",
    "cover": "Projekti/vjencanja-i-zabave/ChatGPT-Image-Mar-11-2026-07_36_42-PM.png",
    "images": [
      "Projekti/vjencanja-i-zabave/ChatGPT-Image-Mar-11-2026-07_36_42-PM.png"
    ],
    "order": 6
  }
];
